apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnectS2I
metadata:
  annotations:
    strimzi.io/use-connector-resources: 'true'
  name: my-connect-cluster
  namespace: default
spec:
  bootstrapServers: 'my-cluster-kafka-bootstrap:9093'
  config:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    config.storage.replication.factor: 1
    config.storage.topic: my-connect-cluster-configs
    offset.storage.replication.factor: 1
    offset.storage.topic: my-connect-cluster-offsets
    status.storage.replication.factor: 1
    status.storage.topic: my-connect-cluster-status
  externalConfiguration:
    volumes:
      - name: es-user-secret
        secret:
          secretName: es-user-secret
      - name: es-truststore-secret
        secret:
          secretName: es-truststore-secret
  jvmOptions:
    javaSystemProperties:
      - name: javax.net.ssl.trustStore
        value: /opt/kafka/external-configuration/es-truststore-secret/truststore.jks
      - name: javax.net.ssl.trustStorePassword
        value: es1234
  replicas: 1
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: my-cluster-cluster-ca-cert
