apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: default
spec:
  entityOperator:
    tlsSidecar:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
    topicOperator:
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 256Mi
    userOperator:
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 256Mi
  kafka:
    tlsSidecar:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
    config:
      log.message.format.version: '2.4'
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1200Mi
      requests:
        cpu: 100m
        memory: 1200Mi
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    version: 2.4.0
    template:
      pod:
        terminationGracePeriodSeconds: 120
    storage:
      type: ephemeral
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    logging:
      loggers:
        log4j.logger.kafka.authorizer.logger: INFO
        log4j.logger.kafka.controller: INFO
      type: inline
  zookeeper:
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
    storage:
      type: ephemeral
    tlsSidecar:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi